import 'package:get/get.dart';
import 'package:hrm_front/common/data/models/emlpyees_model.dart';

class EmployeeController extends GetxController {
  var employees = <Employee>[].obs;

  @override
  void onInit() {
    super.onInit();
    loadEmployees();
  }

  void loadEmployees() {
    employees.addAll([
      Employee(
        firstName: 'John',
        lastName: 'Doe',
        email: 'johndoe@example.com',
        address: '456 Main St, Springfield',
        phone: '0987654321',
        designation: 'Developer',
        departmentId: 2,
        gender: true,
        bankName: 'xyz',
        bankRIB: 'abc123',
        insuranceNumber: '987654321',
        dateOfBirth: '1992-07-23',
        status: true,
        photoUrl: 'assets/images/man4.jpg',
      ),
      Employee(
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'janedoe@example.com',
        address: '789 Elm St, Metropolis',
        phone: '1239876543',
        designation: 'Manager',
        departmentId: 3,
        gender: false,
        bankName: 'bcd',
        bankRIB: 'def456',
        insuranceNumber: '456123789',
        dateOfBirth: '1988-11-15',
        status: true,
        photoUrl: 'assets/images/woman1.jpg',
      ),
      Employee(
        firstName: 'Imane',
        lastName: 'Omari',
        email: 'imane3.omari@gmail.com',
        address: '123 user St, User City',
        phone: '0555555555',
        designation: 'Mobile Developer',
        departmentId: 1,
        gender: true,
        bankName: 'Natixis Banque',
        bankRIB: 'cle',
        insuranceNumber: '222222',
        dateOfBirth: '2001-06-15',
        status: true,
        photoUrl: 'assets/images/woman.jpg',
      ),
      
      
      Employee(
        firstName: 'Alice',
        lastName: 'Smith',
        email: 'alice@example.com',
        address: '123 Oak St, Gotham',
        phone: '2345678901',
        designation: 'Data Analyst',
        departmentId: 4,
        gender: false,
        bankName: 'efg',
        bankRIB: 'ghi789',
        insuranceNumber: '123456000',
        dateOfBirth: '1990-06-10',
        status: true,
        photoUrl: 'assets/images/woman2.jpg',
      ),
      Employee(
        firstName: 'Bob',
        lastName: 'Brown',
        email: 'bob@example.com',
        address: '456 Cedar St, Star City',
        phone: '3456789012',
        designation: 'Consultant',
        departmentId: 5,
        gender: true,
        bankName: 'hij',
        bankRIB: 'klm123',
        insuranceNumber: '0987654321',
        dateOfBirth: '1985-04-08',
        status: true,
        photoUrl: 'assets/images/man2.jpg',
      ),
      Employee(
        firstName: 'Charlie',
        lastName: 'Davis',
        email: 'charlie@example.com',
        address: '789 Willow St, Central City',
        phone: '4567890123',
        designation: 'Intern',
        departmentId: 4,
        gender: true,
        bankName: 'nop',
        bankRIB: 'qrs456',
        insuranceNumber: '2345678901',
        dateOfBirth: '1997-12-25',
        status: true,
        photoUrl: 'assets/images/man1.jpg',
      ),
      Employee(
        firstName: 'Diana',
        lastName: 'Prince',
        email: 'diana@example.com',
        address: '123 Maple St, Themyscira',
        phone: '5678901234',
        designation: 'HR',
        departmentId: 1,
        gender: false,
        bankName: 'tuv',
        bankRIB: 'wxy789',
        insuranceNumber: '3456789012',
        dateOfBirth: '1995-03-14',
        status: true,
        photoUrl: 'assets/images/woman3.jpg',
      ),
      Employee(
        firstName: 'Eve',
        lastName: 'Miller',
        email: 'eve@example.com',
        address: '234 Pine St, National City',
        phone: '6789012345',
        designation: 'Engineer',
        departmentId: 2,
        gender: false,
        bankName: 'xyz',
        bankRIB: 'abc789',
        insuranceNumber: '6789012345',
        dateOfBirth: '1989-01-05',
        status: true,
        photoUrl: 'assets/images/woman4.jpg',
      ),
      Employee(
        firstName: 'Frank',
        lastName: 'Wright',
        email: 'frank@example.com',
        address: '345 Birch St, Smallville',
        phone: '7890123456',
        designation: 'Architect',
        departmentId: 3,
        gender: true,
        bankName: 'uvw',
        bankRIB: 'def012',
        insuranceNumber: '7890123456',
        dateOfBirth: '1987-08-19',
        status: true,
        photoUrl: 'assets/images/man4.jpg',
      ),
      Employee(
        firstName: 'Grace',
        lastName: 'Hill',
        email: 'grace@example.com',
        address: '456 Redwood St, Metropolis',
        phone: '8901234567',
        designation: 'Consultant',
        departmentId: 4,
        gender: false,
        bankName: 'opq',
        bankRIB: 'rst123',
        insuranceNumber: '8901234567',
        dateOfBirth: '1993-10-27',
        status: true,
        photoUrl: 'assets/images/woman5.jpg',
      ),
    ]);
  }
}
